name: Generate and Push Go File to Target

on:
  push:
    branches:
      - main

jobs:
  generate_and_push_to_target:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v3
      with:
        repository: <repo name>
        ref: 'master'
        token:  ${{ secrets.GENERATOR_SECRET }}

    - name: Generate Go File
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
      run: |
        make setup-go

    - name: Commit and Push Generated Go File to Target
      run: |
        git config user.name "muhammad chandra zulfikar"
        git config user.email "muhammadchandrazulfikar@gmail.com"

        # Add the target repository as a remote
        git remote add akira-go-proto https://github.com/MuhammadChandra19/akira-go-proto.git

        rm modules

        cp -r go/modules/* modules

        git add .
        git commit -m "automated go generation"

        # Create a new branch "version" in the target repository
        git push akira-go-proto main