name: Generate and Push Go File to Target

on:
  push:
    branches:
      - master

jobs:
  generate_and_push_to_target:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v3
      
    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install Protoc
      uses: arduino/setup-protoc@v2

    - name: Install protoc-gen-go and mockgen
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
        go install github.com/golang/mock/mockgen@v1.5.0

    - name: update go path
      run: export PATH=$PATH:$(go env GOPATH)/bin

    - name: Verify protoc-gen-go installation
      run: protoc-gen-go --version


    - name: Commit and Push Generated Go File to Target
      run: |
        make run-go-workflow

        git clone https://$GITHUB_TOKEN@github.com/MuhammadChandra19/akira-go-proto.git


        rm -rf akira-go-proto/modules

        mkdir akira-go-proto/modules

        cp -r go/modules/* akira-go-proto/modules

        cd akira-go-proto
        git config user.name "MuhammadChandra19"
        git config user.email "muhammadchandrazulfikar@gmail.com"

        git add .
        git commit -m "automated go generation"

        git push 
      env:
        GITHUB_TOKEN: ${{ secrets.GENERATOR_SECRET }}
